language: java
sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    before_install:
      - brew update
        # This is a workaround because someone broke brew casks... https://github.com/Homebrew/homebrew-cask/issues/49716
      - find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' | xargs grep 'EOS.undent' --files-with-matches | xargs sed -i '' 's/EOS.undent/EOS/'
      - brew cask reinstall java
      - java -version
script: 
  - ./gradlew build
after_success:
  - wget $TRAVIS_DISCORD_WEBHOOK_SCRIPT_URL
  - chmod +x send.sh
  - ./send.sh success $DISCORD_URL
after_failure:
  - wget $TRAVIS_DISCORD_WEBHOOK_SCRIPT_URL
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_URL
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
 - ./gradlew deploy
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASE_KEY
  file_glob: true
  file: releases/release-*/*
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  draft: false
  prerelease: true
  on:
    repo: $REPO
    tags: true
    all_branches: true
