language: java
sudo: false
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8.3
install: true
addons:
  apt:
    packages:
    - oracle-java8-installer
    - fakeroot
script: 
  - ./gradlew build
notifications:
  slack: nerps:JumMHisqOlXac7be25Ca8FbN
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
  - ./gradlew deploy
deploy:
  provider: releases
  api_key:
    secure: reFts6i0FCeE1tQpcUEBT35bnjZjZvbj9mwJBm8qHpjF/obKmFvioQCT8mGPo83n3qTUC+2atOVsiqyEpYfqWXrkk/cy8mySxaGr77czuJVXhboGv5AUFJiJ78ehMs7Rqdxs0TnHq99eBTw3S70vMCQXZQD/N2EcXpmziSP2g/SkAdoLh/i9rshexqczvoEnEidYTlHACVS+09Rr8CGDkjwzU6TxOejUZPmsaETjbGNa8R9tUv7aDDHhloRDkLLDU+bw0ZNcRLadUj6PgjKv+HTtohSS0etsd8HCngF4lqBaV6gQAZ43XEe60YI9X7q083XZchOwC6G53q28GG9GDcSGqp0YLotkX6N/2K7XL6oLgD1Hd/0hPNsN10NFps50hT59312bvUVZiozQtSM+NgSPlljVuepgdBTVilSKoOU1tPaSaQvSndzdjpkDP9Gy8M7Ydci1Ir5wqHjJSlbN6Z0DMJU0xc9y44HLni9YKzUUJHXU3rtSftHpmjStqHaAopvxUPBLJZrjOSCl5wrcVuXAa0gGekOH2WXTDiESp4+h2Afc7KGv0Yj7TTpzJaGpxQH5r/3YOdZdPSn0xciVU0C/dkDhI2Zj+omTuR9iBFCop2AlcmLSmlIcINfZPfMYCH7vdoorXgyciBNMCn3sb/qoffFIIfR1R2krlyR07RY=
  file_glob: true
  file: releases/release-*/bundles/*
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  draft: true
  on:
    repo: JamzTheMan/tokentool
    tags: true
    all_branches: true