name: Publish Assets

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        java: [ '14' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2.1.0
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}
# Cache only seems to work on ubuntu right now...
#     - name: Cache Gradle
#       uses: actions/cache@v1.1.2
#       with:
#         path: ~/.gradle/caches
#         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#         restore-keys: |
#           ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew jpackage
    - name: List releases
      run: ls releases
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
        allowUpdates: true
    - name: Upload Release Assets
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'releases/*.*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}
