name: Publish Assets
on:
  release:
    types:
      - published
jobs:
  build:
    name: ${{ matrix.os }} w/JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        java: [ '14' ]
      fail-fast: false
    steps:
    - name: Git checkout
      uses: actions/checkout@v2.1.0
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Gradle
      uses: actions/cache@v1.1.2
      if: matrix.os == 'ubuntu-latest'  # Cache only seems to work on ubuntu right now...
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew jpackage
    - name: List releases
      run: ls releases
    - name: Test URL
      run: echo ${{ github.event.release.release.upload_url }}
    - name: Upload Windows Release Asset
      id: upload-release-asset-exe
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: releases/TokenTool-${{ github.event.release.tag_name }}.exe
        asset_name: TokenTool-${{ github.event.release.tag_name }}.exe
        asset_content_type: application/octet-stream
    - name: Upload Linux RPM Release Asset
      id: upload-release-asset-rpm
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'ubuntu-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: releases/tokentool-${{ github.event.release.tag_name }}-1.x86_64.rpm
        asset_name: tokentool-${{ github.event.release.tag_name }}-x86_64.rpm
        asset_content_type: application/octet-stream
    - name: Upload Linux DEB Release Asset
      id: upload-release-asset-deb
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'ubuntu-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: releases/tokentool_${{ github.event.release.tag_name }}-1_amd64.deb
        asset_name: tokentool_${{ github.event.release.tag_name }}-amd64.deb
        asset_content_type: application/octet-stream
    - name: Upload Mac DMG Release Asset
      id: upload-release-asset-dmg
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: releases/TokenTool-${{ github.event.release.tag_name }}.dmg
        asset_name: TokenTool-${{ github.event.release.tag_name }}.dmg
        asset_content_type: application/octet-stream
    - name: Upload Mac PKG Release Asset
      id: upload-release-asset-pkg
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: releases/TokenTool-${{ github.event.release.tag_name }}.pkg
        asset_name: TokenTool-${{ github.event.release.tag_name }}.pkg
        asset_content_type: application/octet-stream
    - name: Upload Mac App Release Asset
      id: upload-release-asset-app
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.release.upload_url }}
        asset_path: releases/TokenTool.app
        asset_name: TokenTool-${{ github.event.release.tag_name }}.app
        asset_content_type: application/octet-stream
